openapi:
  baseurl: ${baseurl}
  key: ${key}

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/military_recruit
#    username: root
#    password: root
#    driver-class-name: com.postgresql.Driver