name: server-docker-build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get commit count
        run: echo "count=$(git rev-list --all --count)" >> $GITHUB_ENV

      - name: image name
        run: echo "imagename=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up JRE 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jre

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build bootBuildImage with version
        run: ./gradlew bootBuildImage --imageName=${{ env.imagename }}:${{ env.count }} --createdDate=now

      - name: Docker Push with version
        run: docker push ${{ env.imagename }}:${{ env.count }}

      - name: Docker tag change
        run: docker tag ${{ env.imagename }}:${{ env.count }} ${{ env.imagename }}:latest

      - name: Docker Push with latest
        run: docker push ${{ env.imagename }}:latest